// app/layout.tsx
import type { Metadata } from "next";
import { Poppins } from "next/font/google"; 
import "./globals.css";


const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], 
  style: ['normal', 'italic'], 
  subsets: ['latin'], 
  display: 'swap', 
  variable: '--font-poppins', 
});

export const metadata: Metadata = {
  title: "Login Page",
  description: "Generated by create login page",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}